/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#11131d",
        "surface-variant": "#222532",
        "secondary-fixed": "#ffc3c2",
        "surface-container": "#171924",
        "on-secondary-container": "#ffc1c0",
        "on-primary-fixed": "#000000",
        "tertiary": "#e9aaff",
        "tertiary-container": "#e197fc",
        "on-tertiary-fixed": "#310045",
        "background": "#0c0e17",
        "surface-container-high": "#1c1f2b",
        "secondary": "#fc7c7f",
        "on-secondary-fixed-variant": "#922c33",
        "on-error-container": "#ffb2b9",
        "surface-dim": "#0c0e17",
        "outline": "#737580",
        "surface-tint": "#ff8f73",
        "on-primary-container": "#490b00",
        "primary-fixed": "#ff7856",
        "tertiary-fixed": "#e197fc",
        "surface-container-highest": "#222532",
        "error-dim": "#d73357",
        "tertiary-dim": "#d28aee",
        "inverse-on-surface": "#53545f",
        "surface-bright": "#282b3a",
        "inverse-primary": "#b52900",
        "inverse-surface": "#faf8ff",
        "on-surface": "#f0f0fd",
        "primary": "#ff8f73",
        "on-secondary-fixed": "#6a0e19",
        "primary-fixed-dim": "#ff5c34",
        "on-tertiary-container": "#530c70",
        "tertiary-fixed-dim": "#d28aee",
        "on-tertiary-fixed-variant": "#5d1979",
        "surface": "#0c0e17",
        "on-primary-fixed-variant": "#5a0f00",
        "secondary-container": "#84222a",
        "secondary-dim": "#f5777a",
        "on-error": "#490013",
        "surface-container-lowest": "#000000",
        "on-background": "#f0f0fd",
        "primary-container": "#ff7856",
        "on-secondary": "#53000d",
        "primary-dim": "#dc3300",
        "error": "#ff6e84",
        "on-tertiary": "#5e1b7a",
        "secondary-fixed-dim": "#ffafae",
        "on-surface-variant": "#aaaab7",
        "error-container": "#a70138",
        "on-primary": "#5e1000",
        "outline-variant": "#464752"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}